services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./credentials:/app/credentials

  frontend:
    build: .
    env_file:
      - .env
    command: >
      streamlit run
      frontend/streamlit_app.py
      --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api